// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCatalogParams creates a new DeleteCatalogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCatalogParams() *DeleteCatalogParams {
	return &DeleteCatalogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCatalogParamsWithTimeout creates a new DeleteCatalogParams object
// with the ability to set a timeout on a request.
func NewDeleteCatalogParamsWithTimeout(timeout time.Duration) *DeleteCatalogParams {
	return &DeleteCatalogParams{
		timeout: timeout,
	}
}

// NewDeleteCatalogParamsWithContext creates a new DeleteCatalogParams object
// with the ability to set a context for a request.
func NewDeleteCatalogParamsWithContext(ctx context.Context) *DeleteCatalogParams {
	return &DeleteCatalogParams{
		Context: ctx,
	}
}

// NewDeleteCatalogParamsWithHTTPClient creates a new DeleteCatalogParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCatalogParamsWithHTTPClient(client *http.Client) *DeleteCatalogParams {
	return &DeleteCatalogParams{
		HTTPClient: client,
	}
}

/* DeleteCatalogParams contains all the parameters to send to the API endpoint
   for the delete catalog operation.

   Typically these are written to a http.Request.
*/
type DeleteCatalogParams struct {

	// ID.
	ID string

	// Owner.
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete catalog params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCatalogParams) WithDefaults() *DeleteCatalogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete catalog params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCatalogParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete catalog params
func (o *DeleteCatalogParams) WithTimeout(timeout time.Duration) *DeleteCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete catalog params
func (o *DeleteCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete catalog params
func (o *DeleteCatalogParams) WithContext(ctx context.Context) *DeleteCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete catalog params
func (o *DeleteCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete catalog params
func (o *DeleteCatalogParams) WithHTTPClient(client *http.Client) *DeleteCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete catalog params
func (o *DeleteCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete catalog params
func (o *DeleteCatalogParams) WithID(id string) *DeleteCatalogParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete catalog params
func (o *DeleteCatalogParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the delete catalog params
func (o *DeleteCatalogParams) WithOwner(owner string) *DeleteCatalogParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the delete catalog params
func (o *DeleteCatalogParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
