// Code generated by go-swagger; DO NOT EDIT.

package collections

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCatalogParams creates a new GetCatalogParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCatalogParams() *GetCatalogParams {
	return &GetCatalogParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCatalogParamsWithTimeout creates a new GetCatalogParams object
// with the ability to set a timeout on a request.
func NewGetCatalogParamsWithTimeout(timeout time.Duration) *GetCatalogParams {
	return &GetCatalogParams{
		timeout: timeout,
	}
}

// NewGetCatalogParamsWithContext creates a new GetCatalogParams object
// with the ability to set a context for a request.
func NewGetCatalogParamsWithContext(ctx context.Context) *GetCatalogParams {
	return &GetCatalogParams{
		Context: ctx,
	}
}

// NewGetCatalogParamsWithHTTPClient creates a new GetCatalogParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCatalogParamsWithHTTPClient(client *http.Client) *GetCatalogParams {
	return &GetCatalogParams{
		HTTPClient: client,
	}
}

/* GetCatalogParams contains all the parameters to send to the API endpoint
   for the get catalog operation.

   Typically these are written to a http.Request.
*/
type GetCatalogParams struct {

	// ID.
	ID string

	// Owner.
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get catalog params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCatalogParams) WithDefaults() *GetCatalogParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get catalog params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCatalogParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get catalog params
func (o *GetCatalogParams) WithTimeout(timeout time.Duration) *GetCatalogParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get catalog params
func (o *GetCatalogParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get catalog params
func (o *GetCatalogParams) WithContext(ctx context.Context) *GetCatalogParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get catalog params
func (o *GetCatalogParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get catalog params
func (o *GetCatalogParams) WithHTTPClient(client *http.Client) *GetCatalogParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get catalog params
func (o *GetCatalogParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get catalog params
func (o *GetCatalogParams) WithID(id string) *GetCatalogParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get catalog params
func (o *GetCatalogParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the get catalog params
func (o *GetCatalogParams) WithOwner(owner string) *GetCatalogParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get catalog params
func (o *GetCatalogParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *GetCatalogParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
