// Code generated by go-swagger; DO NOT EDIT.

package d_o_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddVersionDoiParams creates a new AddVersionDoiParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddVersionDoiParams() *AddVersionDoiParams {
	return &AddVersionDoiParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddVersionDoiParamsWithTimeout creates a new AddVersionDoiParams object
// with the ability to set a timeout on a request.
func NewAddVersionDoiParamsWithTimeout(timeout time.Duration) *AddVersionDoiParams {
	return &AddVersionDoiParams{
		timeout: timeout,
	}
}

// NewAddVersionDoiParamsWithContext creates a new AddVersionDoiParams object
// with the ability to set a context for a request.
func NewAddVersionDoiParamsWithContext(ctx context.Context) *AddVersionDoiParams {
	return &AddVersionDoiParams{
		Context: ctx,
	}
}

// NewAddVersionDoiParamsWithHTTPClient creates a new AddVersionDoiParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddVersionDoiParamsWithHTTPClient(client *http.Client) *AddVersionDoiParams {
	return &AddVersionDoiParams{
		HTTPClient: client,
	}
}

/* AddVersionDoiParams contains all the parameters to send to the API endpoint
   for the add version doi operation.

   Typically these are written to a http.Request.
*/
type AddVersionDoiParams struct {

	// Doi.
	Doi string

	// ID.
	ID string

	// Owner.
	Owner string

	// VersionID.
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add version doi params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddVersionDoiParams) WithDefaults() *AddVersionDoiParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add version doi params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddVersionDoiParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add version doi params
func (o *AddVersionDoiParams) WithTimeout(timeout time.Duration) *AddVersionDoiParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add version doi params
func (o *AddVersionDoiParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add version doi params
func (o *AddVersionDoiParams) WithContext(ctx context.Context) *AddVersionDoiParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add version doi params
func (o *AddVersionDoiParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add version doi params
func (o *AddVersionDoiParams) WithHTTPClient(client *http.Client) *AddVersionDoiParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add version doi params
func (o *AddVersionDoiParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDoi adds the doi to the add version doi params
func (o *AddVersionDoiParams) WithDoi(doi string) *AddVersionDoiParams {
	o.SetDoi(doi)
	return o
}

// SetDoi adds the doi to the add version doi params
func (o *AddVersionDoiParams) SetDoi(doi string) {
	o.Doi = doi
}

// WithID adds the id to the add version doi params
func (o *AddVersionDoiParams) WithID(id string) *AddVersionDoiParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the add version doi params
func (o *AddVersionDoiParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the add version doi params
func (o *AddVersionDoiParams) WithOwner(owner string) *AddVersionDoiParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the add version doi params
func (o *AddVersionDoiParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithVersionID adds the versionID to the add version doi params
func (o *AddVersionDoiParams) WithVersionID(versionID string) *AddVersionDoiParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the add version doi params
func (o *AddVersionDoiParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *AddVersionDoiParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param doi
	if err := r.SetPathParam("doi", o.Doi); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
