// Code generated by go-swagger; DO NOT EDIT.

package d_o_is

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// DeleteDoiReader is a Reader for the DeleteDoi structure.
type DeleteDoiReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDoiReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteDoiOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteDoiBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteDoiUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteDoiForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteDoiNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteDoiInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteDoiOK creates a DeleteDoiOK with default headers values
func NewDeleteDoiOK() *DeleteDoiOK {
	return &DeleteDoiOK{}
}

/* DeleteDoiOK describes a response with status code 200, with default header values.

DOI successfully removed from dataset.
*/
type DeleteDoiOK struct {
	Payload *models.SuccessMessage
}

func (o *DeleteDoiOK) Error() string {
	return fmt.Sprintf("[DELETE /datasets/{owner}/{id}/dois/{doi}][%d] deleteDoiOK  %+v", 200, o.Payload)
}
func (o *DeleteDoiOK) GetPayload() *models.SuccessMessage {
	return o.Payload
}

func (o *DeleteDoiOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDoiBadRequest creates a DeleteDoiBadRequest with default headers values
func NewDeleteDoiBadRequest() *DeleteDoiBadRequest {
	return &DeleteDoiBadRequest{}
}

/* DeleteDoiBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type DeleteDoiBadRequest struct {
	Payload *models.ErrorMessage
}

func (o *DeleteDoiBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /datasets/{owner}/{id}/dois/{doi}][%d] deleteDoiBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteDoiBadRequest) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteDoiBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDoiUnauthorized creates a DeleteDoiUnauthorized with default headers values
func NewDeleteDoiUnauthorized() *DeleteDoiUnauthorized {
	return &DeleteDoiUnauthorized{}
}

/* DeleteDoiUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteDoiUnauthorized struct {
	Payload *models.ErrorMessage
}

func (o *DeleteDoiUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /datasets/{owner}/{id}/dois/{doi}][%d] deleteDoiUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteDoiUnauthorized) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteDoiUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDoiForbidden creates a DeleteDoiForbidden with default headers values
func NewDeleteDoiForbidden() *DeleteDoiForbidden {
	return &DeleteDoiForbidden{}
}

/* DeleteDoiForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteDoiForbidden struct {
	Payload *models.ErrorMessage
}

func (o *DeleteDoiForbidden) Error() string {
	return fmt.Sprintf("[DELETE /datasets/{owner}/{id}/dois/{doi}][%d] deleteDoiForbidden  %+v", 403, o.Payload)
}
func (o *DeleteDoiForbidden) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteDoiForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDoiNotFound creates a DeleteDoiNotFound with default headers values
func NewDeleteDoiNotFound() *DeleteDoiNotFound {
	return &DeleteDoiNotFound{}
}

/* DeleteDoiNotFound describes a response with status code 404, with default header values.

Not found
*/
type DeleteDoiNotFound struct {
	Payload *models.ErrorMessage
}

func (o *DeleteDoiNotFound) Error() string {
	return fmt.Sprintf("[DELETE /datasets/{owner}/{id}/dois/{doi}][%d] deleteDoiNotFound  %+v", 404, o.Payload)
}
func (o *DeleteDoiNotFound) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteDoiNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteDoiInternalServerError creates a DeleteDoiInternalServerError with default headers values
func NewDeleteDoiInternalServerError() *DeleteDoiInternalServerError {
	return &DeleteDoiInternalServerError{}
}

/* DeleteDoiInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type DeleteDoiInternalServerError struct {
	Payload *models.ErrorMessage
}

func (o *DeleteDoiInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /datasets/{owner}/{id}/dois/{doi}][%d] deleteDoiInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteDoiInternalServerError) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteDoiInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
