// Code generated by go-swagger; DO NOT EDIT.

package describe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new describe API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for describe API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	Describe(params *DescribeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DescribeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  Describe s p a r q l d e s c r i b e query

  This endpoint executes a SPARQL DESCRIBE query, given an IRI.
.
*/
func (a *Client) Describe(params *DescribeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DescribeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDescribeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "describe",
		Method:             "GET",
		PathPattern:        "/describe",
		ProducesMediaTypes: []string{"application/rdf+json", "application/rdf+xml", "application/sparql-results+json", "application/sparql-results+xml", "text/csv", "text/tab-separated-values", "text/turtle"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DescribeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DescribeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for describe: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
