// Code generated by go-swagger; DO NOT EDIT.

package serviceaccount

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// DeleteServiceAccountReader is a Reader for the DeleteServiceAccount structure.
type DeleteServiceAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteServiceAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteServiceAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteServiceAccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteServiceAccountUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteServiceAccountForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteServiceAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteServiceAccountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteServiceAccountOK creates a DeleteServiceAccountOK with default headers values
func NewDeleteServiceAccountOK() *DeleteServiceAccountOK {
	return &DeleteServiceAccountOK{}
}

/* DeleteServiceAccountOK describes a response with status code 200, with default header values.

Successfully deleted service account
*/
type DeleteServiceAccountOK struct {
	Payload *models.SuccessMessage
}

func (o *DeleteServiceAccountOK) Error() string {
	return fmt.Sprintf("[DELETE /serviceaccount/{owner}/{serviceAccount}][%d] deleteServiceAccountOK  %+v", 200, o.Payload)
}
func (o *DeleteServiceAccountOK) GetPayload() *models.SuccessMessage {
	return o.Payload
}

func (o *DeleteServiceAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteServiceAccountBadRequest creates a DeleteServiceAccountBadRequest with default headers values
func NewDeleteServiceAccountBadRequest() *DeleteServiceAccountBadRequest {
	return &DeleteServiceAccountBadRequest{}
}

/* DeleteServiceAccountBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type DeleteServiceAccountBadRequest struct {
	Payload *models.ErrorMessage
}

func (o *DeleteServiceAccountBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /serviceaccount/{owner}/{serviceAccount}][%d] deleteServiceAccountBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteServiceAccountBadRequest) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteServiceAccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteServiceAccountUnauthorized creates a DeleteServiceAccountUnauthorized with default headers values
func NewDeleteServiceAccountUnauthorized() *DeleteServiceAccountUnauthorized {
	return &DeleteServiceAccountUnauthorized{}
}

/* DeleteServiceAccountUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteServiceAccountUnauthorized struct {
	Payload *models.ErrorMessage
}

func (o *DeleteServiceAccountUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /serviceaccount/{owner}/{serviceAccount}][%d] deleteServiceAccountUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteServiceAccountUnauthorized) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteServiceAccountUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteServiceAccountForbidden creates a DeleteServiceAccountForbidden with default headers values
func NewDeleteServiceAccountForbidden() *DeleteServiceAccountForbidden {
	return &DeleteServiceAccountForbidden{}
}

/* DeleteServiceAccountForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteServiceAccountForbidden struct {
	Payload *models.ErrorMessage
}

func (o *DeleteServiceAccountForbidden) Error() string {
	return fmt.Sprintf("[DELETE /serviceaccount/{owner}/{serviceAccount}][%d] deleteServiceAccountForbidden  %+v", 403, o.Payload)
}
func (o *DeleteServiceAccountForbidden) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteServiceAccountForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteServiceAccountNotFound creates a DeleteServiceAccountNotFound with default headers values
func NewDeleteServiceAccountNotFound() *DeleteServiceAccountNotFound {
	return &DeleteServiceAccountNotFound{}
}

/* DeleteServiceAccountNotFound describes a response with status code 404, with default header values.

Not found
*/
type DeleteServiceAccountNotFound struct {
	Payload *models.ErrorMessage
}

func (o *DeleteServiceAccountNotFound) Error() string {
	return fmt.Sprintf("[DELETE /serviceaccount/{owner}/{serviceAccount}][%d] deleteServiceAccountNotFound  %+v", 404, o.Payload)
}
func (o *DeleteServiceAccountNotFound) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteServiceAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteServiceAccountInternalServerError creates a DeleteServiceAccountInternalServerError with default headers values
func NewDeleteServiceAccountInternalServerError() *DeleteServiceAccountInternalServerError {
	return &DeleteServiceAccountInternalServerError{}
}

/* DeleteServiceAccountInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type DeleteServiceAccountInternalServerError struct {
	Payload *models.ErrorMessage
}

func (o *DeleteServiceAccountInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /serviceaccount/{owner}/{serviceAccount}][%d] deleteServiceAccountInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteServiceAccountInternalServerError) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteServiceAccountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
