// Code generated by go-swagger; DO NOT EDIT.

package sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTableParams creates a new GetTableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTableParams() *GetTableParams {
	return &GetTableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTableParamsWithTimeout creates a new GetTableParams object
// with the ability to set a timeout on a request.
func NewGetTableParamsWithTimeout(timeout time.Duration) *GetTableParams {
	return &GetTableParams{
		timeout: timeout,
	}
}

// NewGetTableParamsWithContext creates a new GetTableParams object
// with the ability to set a context for a request.
func NewGetTableParamsWithContext(ctx context.Context) *GetTableParams {
	return &GetTableParams{
		Context: ctx,
	}
}

// NewGetTableParamsWithHTTPClient creates a new GetTableParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTableParamsWithHTTPClient(client *http.Client) *GetTableParams {
	return &GetTableParams{
		HTTPClient: client,
	}
}

/* GetTableParams contains all the parameters to send to the API endpoint
   for the get table operation.

   Typically these are written to a http.Request.
*/
type GetTableParams struct {

	/* Owner.

	   id of the user or organization
	*/
	Owner string

	/* Sourceid.

	   database source id
	*/
	Sourceid string

	// Tableid.
	Tableid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get table params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTableParams) WithDefaults() *GetTableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get table params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get table params
func (o *GetTableParams) WithTimeout(timeout time.Duration) *GetTableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get table params
func (o *GetTableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get table params
func (o *GetTableParams) WithContext(ctx context.Context) *GetTableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get table params
func (o *GetTableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get table params
func (o *GetTableParams) WithHTTPClient(client *http.Client) *GetTableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get table params
func (o *GetTableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwner adds the owner to the get table params
func (o *GetTableParams) WithOwner(owner string) *GetTableParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get table params
func (o *GetTableParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithSourceid adds the sourceid to the get table params
func (o *GetTableParams) WithSourceid(sourceid string) *GetTableParams {
	o.SetSourceid(sourceid)
	return o
}

// SetSourceid adds the sourceid to the get table params
func (o *GetTableParams) SetSourceid(sourceid string) {
	o.Sourceid = sourceid
}

// WithTableid adds the tableid to the get table params
func (o *GetTableParams) WithTableid(tableid string) *GetTableParams {
	o.SetTableid(tableid)
	return o
}

// SetTableid adds the tableid to the get table params
func (o *GetTableParams) SetTableid(tableid string) {
	o.Tableid = tableid
}

// WriteToRequest writes these params to a swagger request
func (o *GetTableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param sourceid
	if err := r.SetPathParam("sourceid", o.Sourceid); err != nil {
		return err
	}

	// path param tableid
	if err := r.SetPathParam("tableid", o.Tableid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
