// Code generated by go-swagger; DO NOT EDIT.

package sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// NewPatchCatalogColumnParams creates a new PatchCatalogColumnParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchCatalogColumnParams() *PatchCatalogColumnParams {
	return &PatchCatalogColumnParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchCatalogColumnParamsWithTimeout creates a new PatchCatalogColumnParams object
// with the ability to set a timeout on a request.
func NewPatchCatalogColumnParamsWithTimeout(timeout time.Duration) *PatchCatalogColumnParams {
	return &PatchCatalogColumnParams{
		timeout: timeout,
	}
}

// NewPatchCatalogColumnParamsWithContext creates a new PatchCatalogColumnParams object
// with the ability to set a context for a request.
func NewPatchCatalogColumnParamsWithContext(ctx context.Context) *PatchCatalogColumnParams {
	return &PatchCatalogColumnParams{
		Context: ctx,
	}
}

// NewPatchCatalogColumnParamsWithHTTPClient creates a new PatchCatalogColumnParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchCatalogColumnParamsWithHTTPClient(client *http.Client) *PatchCatalogColumnParams {
	return &PatchCatalogColumnParams{
		HTTPClient: client,
	}
}

/* PatchCatalogColumnParams contains all the parameters to send to the API endpoint
   for the patch catalog column operation.

   Typically these are written to a http.Request.
*/
type PatchCatalogColumnParams struct {

	// Body.
	Body *models.CatalogColumnRequest

	// Columnid.
	Columnid string

	/* Owner.

	   id of the user or organization
	*/
	Owner string

	/* Sourceid.

	   database source id
	*/
	Sourceid string

	// Tableid.
	Tableid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch catalog column params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchCatalogColumnParams) WithDefaults() *PatchCatalogColumnParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch catalog column params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchCatalogColumnParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch catalog column params
func (o *PatchCatalogColumnParams) WithTimeout(timeout time.Duration) *PatchCatalogColumnParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch catalog column params
func (o *PatchCatalogColumnParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch catalog column params
func (o *PatchCatalogColumnParams) WithContext(ctx context.Context) *PatchCatalogColumnParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch catalog column params
func (o *PatchCatalogColumnParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch catalog column params
func (o *PatchCatalogColumnParams) WithHTTPClient(client *http.Client) *PatchCatalogColumnParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch catalog column params
func (o *PatchCatalogColumnParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch catalog column params
func (o *PatchCatalogColumnParams) WithBody(body *models.CatalogColumnRequest) *PatchCatalogColumnParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch catalog column params
func (o *PatchCatalogColumnParams) SetBody(body *models.CatalogColumnRequest) {
	o.Body = body
}

// WithColumnid adds the columnid to the patch catalog column params
func (o *PatchCatalogColumnParams) WithColumnid(columnid string) *PatchCatalogColumnParams {
	o.SetColumnid(columnid)
	return o
}

// SetColumnid adds the columnid to the patch catalog column params
func (o *PatchCatalogColumnParams) SetColumnid(columnid string) {
	o.Columnid = columnid
}

// WithOwner adds the owner to the patch catalog column params
func (o *PatchCatalogColumnParams) WithOwner(owner string) *PatchCatalogColumnParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the patch catalog column params
func (o *PatchCatalogColumnParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithSourceid adds the sourceid to the patch catalog column params
func (o *PatchCatalogColumnParams) WithSourceid(sourceid string) *PatchCatalogColumnParams {
	o.SetSourceid(sourceid)
	return o
}

// SetSourceid adds the sourceid to the patch catalog column params
func (o *PatchCatalogColumnParams) SetSourceid(sourceid string) {
	o.Sourceid = sourceid
}

// WithTableid adds the tableid to the patch catalog column params
func (o *PatchCatalogColumnParams) WithTableid(tableid string) *PatchCatalogColumnParams {
	o.SetTableid(tableid)
	return o
}

// SetTableid adds the tableid to the patch catalog column params
func (o *PatchCatalogColumnParams) SetTableid(tableid string) {
	o.Tableid = tableid
}

// WriteToRequest writes these params to a swagger request
func (o *PatchCatalogColumnParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param columnid
	if err := r.SetPathParam("columnid", o.Columnid); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param sourceid
	if err := r.SetPathParam("sourceid", o.Sourceid); err != nil {
		return err
	}

	// path param tableid
	if err := r.SetPathParam("tableid", o.Tableid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
