// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteProjectSavedQueryParams creates a new DeleteProjectSavedQueryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProjectSavedQueryParams() *DeleteProjectSavedQueryParams {
	return &DeleteProjectSavedQueryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProjectSavedQueryParamsWithTimeout creates a new DeleteProjectSavedQueryParams object
// with the ability to set a timeout on a request.
func NewDeleteProjectSavedQueryParamsWithTimeout(timeout time.Duration) *DeleteProjectSavedQueryParams {
	return &DeleteProjectSavedQueryParams{
		timeout: timeout,
	}
}

// NewDeleteProjectSavedQueryParamsWithContext creates a new DeleteProjectSavedQueryParams object
// with the ability to set a context for a request.
func NewDeleteProjectSavedQueryParamsWithContext(ctx context.Context) *DeleteProjectSavedQueryParams {
	return &DeleteProjectSavedQueryParams{
		Context: ctx,
	}
}

// NewDeleteProjectSavedQueryParamsWithHTTPClient creates a new DeleteProjectSavedQueryParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProjectSavedQueryParamsWithHTTPClient(client *http.Client) *DeleteProjectSavedQueryParams {
	return &DeleteProjectSavedQueryParams{
		HTTPClient: client,
	}
}

/* DeleteProjectSavedQueryParams contains all the parameters to send to the API endpoint
   for the delete project saved query operation.

   Typically these are written to a http.Request.
*/
type DeleteProjectSavedQueryParams struct {

	// ID.
	ID string

	// Owner.
	Owner string

	// QueryID.
	QueryID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete project saved query params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectSavedQueryParams) WithDefaults() *DeleteProjectSavedQueryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete project saved query params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProjectSavedQueryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) WithTimeout(timeout time.Duration) *DeleteProjectSavedQueryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) WithContext(ctx context.Context) *DeleteProjectSavedQueryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) WithHTTPClient(client *http.Client) *DeleteProjectSavedQueryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) WithID(id string) *DeleteProjectSavedQueryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) WithOwner(owner string) *DeleteProjectSavedQueryParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithQueryID adds the queryID to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) WithQueryID(queryID string) *DeleteProjectSavedQueryParams {
	o.SetQueryID(queryID)
	return o
}

// SetQueryID adds the queryId to the delete project saved query params
func (o *DeleteProjectSavedQueryParams) SetQueryID(queryID string) {
	o.QueryID = queryID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProjectSavedQueryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param queryId
	if err := r.SetPathParam("queryId", o.QueryID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
