// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetProjectQueriesParams creates a new GetProjectQueriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetProjectQueriesParams() *GetProjectQueriesParams {
	return &GetProjectQueriesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectQueriesParamsWithTimeout creates a new GetProjectQueriesParams object
// with the ability to set a timeout on a request.
func NewGetProjectQueriesParamsWithTimeout(timeout time.Duration) *GetProjectQueriesParams {
	return &GetProjectQueriesParams{
		timeout: timeout,
	}
}

// NewGetProjectQueriesParamsWithContext creates a new GetProjectQueriesParams object
// with the ability to set a context for a request.
func NewGetProjectQueriesParamsWithContext(ctx context.Context) *GetProjectQueriesParams {
	return &GetProjectQueriesParams{
		Context: ctx,
	}
}

// NewGetProjectQueriesParamsWithHTTPClient creates a new GetProjectQueriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetProjectQueriesParamsWithHTTPClient(client *http.Client) *GetProjectQueriesParams {
	return &GetProjectQueriesParams{
		HTTPClient: client,
	}
}

/* GetProjectQueriesParams contains all the parameters to send to the API endpoint
   for the get project queries operation.

   Typically these are written to a http.Request.
*/
type GetProjectQueriesParams struct {

	// ID.
	ID string

	// Limit.
	Limit *string

	// Next.
	Next *string

	// Owner.
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get project queries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectQueriesParams) WithDefaults() *GetProjectQueriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get project queries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetProjectQueriesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get project queries params
func (o *GetProjectQueriesParams) WithTimeout(timeout time.Duration) *GetProjectQueriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get project queries params
func (o *GetProjectQueriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get project queries params
func (o *GetProjectQueriesParams) WithContext(ctx context.Context) *GetProjectQueriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get project queries params
func (o *GetProjectQueriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get project queries params
func (o *GetProjectQueriesParams) WithHTTPClient(client *http.Client) *GetProjectQueriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get project queries params
func (o *GetProjectQueriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get project queries params
func (o *GetProjectQueriesParams) WithID(id string) *GetProjectQueriesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get project queries params
func (o *GetProjectQueriesParams) SetID(id string) {
	o.ID = id
}

// WithLimit adds the limit to the get project queries params
func (o *GetProjectQueriesParams) WithLimit(limit *string) *GetProjectQueriesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get project queries params
func (o *GetProjectQueriesParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithNext adds the next to the get project queries params
func (o *GetProjectQueriesParams) WithNext(next *string) *GetProjectQueriesParams {
	o.SetNext(next)
	return o
}

// SetNext adds the next to the get project queries params
func (o *GetProjectQueriesParams) SetNext(next *string) {
	o.Next = next
}

// WithOwner adds the owner to the get project queries params
func (o *GetProjectQueriesParams) WithOwner(owner string) *GetProjectQueriesParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get project queries params
func (o *GetProjectQueriesParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectQueriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Next != nil {

		// query param next
		var qrNext string

		if o.Next != nil {
			qrNext = *o.Next
		}
		qNext := qrNext
		if qNext != "" {

			if err := r.SetQueryParam("next", qNext); err != nil {
				return err
			}
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
