// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// GetProjectReader is a Reader for the GetProject structure.
type GetProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetProjectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetProjectUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetProjectForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetProjectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetProjectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetProjectOK creates a GetProjectOK with default headers values
func NewGetProjectOK() *GetProjectOK {
	return &GetProjectOK{}
}

/* GetProjectOK describes a response with status code 200, with default header values.

Successfully retrieved project
*/
type GetProjectOK struct {
	Payload *models.ProjectSummaryResponse
}

func (o *GetProjectOK) Error() string {
	return fmt.Sprintf("[GET /projects/{owner}/{id}][%d] getProjectOK  %+v", 200, o.Payload)
}
func (o *GetProjectOK) GetPayload() *models.ProjectSummaryResponse {
	return o.Payload
}

func (o *GetProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectSummaryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectBadRequest creates a GetProjectBadRequest with default headers values
func NewGetProjectBadRequest() *GetProjectBadRequest {
	return &GetProjectBadRequest{}
}

/* GetProjectBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetProjectBadRequest struct {
	Payload *models.ErrorMessage
}

func (o *GetProjectBadRequest) Error() string {
	return fmt.Sprintf("[GET /projects/{owner}/{id}][%d] getProjectBadRequest  %+v", 400, o.Payload)
}
func (o *GetProjectBadRequest) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *GetProjectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectUnauthorized creates a GetProjectUnauthorized with default headers values
func NewGetProjectUnauthorized() *GetProjectUnauthorized {
	return &GetProjectUnauthorized{}
}

/* GetProjectUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetProjectUnauthorized struct {
	Payload *models.ErrorMessage
}

func (o *GetProjectUnauthorized) Error() string {
	return fmt.Sprintf("[GET /projects/{owner}/{id}][%d] getProjectUnauthorized  %+v", 401, o.Payload)
}
func (o *GetProjectUnauthorized) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *GetProjectUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectForbidden creates a GetProjectForbidden with default headers values
func NewGetProjectForbidden() *GetProjectForbidden {
	return &GetProjectForbidden{}
}

/* GetProjectForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetProjectForbidden struct {
	Payload *models.ErrorMessage
}

func (o *GetProjectForbidden) Error() string {
	return fmt.Sprintf("[GET /projects/{owner}/{id}][%d] getProjectForbidden  %+v", 403, o.Payload)
}
func (o *GetProjectForbidden) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *GetProjectForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectNotFound creates a GetProjectNotFound with default headers values
func NewGetProjectNotFound() *GetProjectNotFound {
	return &GetProjectNotFound{}
}

/* GetProjectNotFound describes a response with status code 404, with default header values.

Not found
*/
type GetProjectNotFound struct {
	Payload *models.ErrorMessage
}

func (o *GetProjectNotFound) Error() string {
	return fmt.Sprintf("[GET /projects/{owner}/{id}][%d] getProjectNotFound  %+v", 404, o.Payload)
}
func (o *GetProjectNotFound) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *GetProjectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectInternalServerError creates a GetProjectInternalServerError with default headers values
func NewGetProjectInternalServerError() *GetProjectInternalServerError {
	return &GetProjectInternalServerError{}
}

/* GetProjectInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type GetProjectInternalServerError struct {
	Payload *models.ErrorMessage
}

func (o *GetProjectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /projects/{owner}/{id}][%d] getProjectInternalServerError  %+v", 500, o.Payload)
}
func (o *GetProjectInternalServerError) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *GetProjectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
