// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// NewReplaceProjectParams creates a new ReplaceProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReplaceProjectParams() *ReplaceProjectParams {
	return &ReplaceProjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceProjectParamsWithTimeout creates a new ReplaceProjectParams object
// with the ability to set a timeout on a request.
func NewReplaceProjectParamsWithTimeout(timeout time.Duration) *ReplaceProjectParams {
	return &ReplaceProjectParams{
		timeout: timeout,
	}
}

// NewReplaceProjectParamsWithContext creates a new ReplaceProjectParams object
// with the ability to set a context for a request.
func NewReplaceProjectParamsWithContext(ctx context.Context) *ReplaceProjectParams {
	return &ReplaceProjectParams{
		Context: ctx,
	}
}

// NewReplaceProjectParamsWithHTTPClient creates a new ReplaceProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewReplaceProjectParamsWithHTTPClient(client *http.Client) *ReplaceProjectParams {
	return &ReplaceProjectParams{
		HTTPClient: client,
	}
}

/* ReplaceProjectParams contains all the parameters to send to the API endpoint
   for the replace project operation.

   Typically these are written to a http.Request.
*/
type ReplaceProjectParams struct {

	// Body.
	Body *models.ProjectPutRequest

	// ID.
	ID string

	// Owner.
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the replace project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceProjectParams) WithDefaults() *ReplaceProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the replace project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the replace project params
func (o *ReplaceProjectParams) WithTimeout(timeout time.Duration) *ReplaceProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace project params
func (o *ReplaceProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace project params
func (o *ReplaceProjectParams) WithContext(ctx context.Context) *ReplaceProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace project params
func (o *ReplaceProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace project params
func (o *ReplaceProjectParams) WithHTTPClient(client *http.Client) *ReplaceProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace project params
func (o *ReplaceProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace project params
func (o *ReplaceProjectParams) WithBody(body *models.ProjectPutRequest) *ReplaceProjectParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace project params
func (o *ReplaceProjectParams) SetBody(body *models.ProjectPutRequest) {
	o.Body = body
}

// WithID adds the id to the replace project params
func (o *ReplaceProjectParams) WithID(id string) *ReplaceProjectParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace project params
func (o *ReplaceProjectParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the replace project params
func (o *ReplaceProjectParams) WithOwner(owner string) *ReplaceProjectParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the replace project params
func (o *ReplaceProjectParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
