// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// NewPatchStreamSchemaParams creates a new PatchStreamSchemaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchStreamSchemaParams() *PatchStreamSchemaParams {
	return &PatchStreamSchemaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchStreamSchemaParamsWithTimeout creates a new PatchStreamSchemaParams object
// with the ability to set a timeout on a request.
func NewPatchStreamSchemaParamsWithTimeout(timeout time.Duration) *PatchStreamSchemaParams {
	return &PatchStreamSchemaParams{
		timeout: timeout,
	}
}

// NewPatchStreamSchemaParamsWithContext creates a new PatchStreamSchemaParams object
// with the ability to set a context for a request.
func NewPatchStreamSchemaParamsWithContext(ctx context.Context) *PatchStreamSchemaParams {
	return &PatchStreamSchemaParams{
		Context: ctx,
	}
}

// NewPatchStreamSchemaParamsWithHTTPClient creates a new PatchStreamSchemaParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchStreamSchemaParamsWithHTTPClient(client *http.Client) *PatchStreamSchemaParams {
	return &PatchStreamSchemaParams{
		HTTPClient: client,
	}
}

/* PatchStreamSchemaParams contains all the parameters to send to the API endpoint
   for the patch stream schema operation.

   Typically these are written to a http.Request.
*/
type PatchStreamSchemaParams struct {

	// Body.
	Body *models.StreamSchemaPatchRequest

	// ID.
	ID string

	// Owner.
	Owner string

	// StreamID.
	StreamID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch stream schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchStreamSchemaParams) WithDefaults() *PatchStreamSchemaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch stream schema params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchStreamSchemaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch stream schema params
func (o *PatchStreamSchemaParams) WithTimeout(timeout time.Duration) *PatchStreamSchemaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch stream schema params
func (o *PatchStreamSchemaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch stream schema params
func (o *PatchStreamSchemaParams) WithContext(ctx context.Context) *PatchStreamSchemaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch stream schema params
func (o *PatchStreamSchemaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch stream schema params
func (o *PatchStreamSchemaParams) WithHTTPClient(client *http.Client) *PatchStreamSchemaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch stream schema params
func (o *PatchStreamSchemaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch stream schema params
func (o *PatchStreamSchemaParams) WithBody(body *models.StreamSchemaPatchRequest) *PatchStreamSchemaParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch stream schema params
func (o *PatchStreamSchemaParams) SetBody(body *models.StreamSchemaPatchRequest) {
	o.Body = body
}

// WithID adds the id to the patch stream schema params
func (o *PatchStreamSchemaParams) WithID(id string) *PatchStreamSchemaParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch stream schema params
func (o *PatchStreamSchemaParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the patch stream schema params
func (o *PatchStreamSchemaParams) WithOwner(owner string) *PatchStreamSchemaParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the patch stream schema params
func (o *PatchStreamSchemaParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithStreamID adds the streamID to the patch stream schema params
func (o *PatchStreamSchemaParams) WithStreamID(streamID string) *PatchStreamSchemaParams {
	o.SetStreamID(streamID)
	return o
}

// SetStreamID adds the streamId to the patch stream schema params
func (o *PatchStreamSchemaParams) SetStreamID(streamID string) {
	o.StreamID = streamID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchStreamSchemaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param streamId
	if err := r.SetPathParam("streamId", o.StreamID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
