// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInsightByVersionParams creates a new GetInsightByVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInsightByVersionParams() *GetInsightByVersionParams {
	return &GetInsightByVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInsightByVersionParamsWithTimeout creates a new GetInsightByVersionParams object
// with the ability to set a timeout on a request.
func NewGetInsightByVersionParamsWithTimeout(timeout time.Duration) *GetInsightByVersionParams {
	return &GetInsightByVersionParams{
		timeout: timeout,
	}
}

// NewGetInsightByVersionParamsWithContext creates a new GetInsightByVersionParams object
// with the ability to set a context for a request.
func NewGetInsightByVersionParamsWithContext(ctx context.Context) *GetInsightByVersionParams {
	return &GetInsightByVersionParams{
		Context: ctx,
	}
}

// NewGetInsightByVersionParamsWithHTTPClient creates a new GetInsightByVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInsightByVersionParamsWithHTTPClient(client *http.Client) *GetInsightByVersionParams {
	return &GetInsightByVersionParams{
		HTTPClient: client,
	}
}

/* GetInsightByVersionParams contains all the parameters to send to the API endpoint
   for the get insight by version operation.

   Typically these are written to a http.Request.
*/
type GetInsightByVersionParams struct {

	// ID.
	ID string

	// ProjectID.
	ProjectID string

	// ProjectOwner.
	ProjectOwner string

	// VersionID.
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get insight by version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInsightByVersionParams) WithDefaults() *GetInsightByVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get insight by version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInsightByVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get insight by version params
func (o *GetInsightByVersionParams) WithTimeout(timeout time.Duration) *GetInsightByVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get insight by version params
func (o *GetInsightByVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get insight by version params
func (o *GetInsightByVersionParams) WithContext(ctx context.Context) *GetInsightByVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get insight by version params
func (o *GetInsightByVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get insight by version params
func (o *GetInsightByVersionParams) WithHTTPClient(client *http.Client) *GetInsightByVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get insight by version params
func (o *GetInsightByVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get insight by version params
func (o *GetInsightByVersionParams) WithID(id string) *GetInsightByVersionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get insight by version params
func (o *GetInsightByVersionParams) SetID(id string) {
	o.ID = id
}

// WithProjectID adds the projectID to the get insight by version params
func (o *GetInsightByVersionParams) WithProjectID(projectID string) *GetInsightByVersionParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get insight by version params
func (o *GetInsightByVersionParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WithProjectOwner adds the projectOwner to the get insight by version params
func (o *GetInsightByVersionParams) WithProjectOwner(projectOwner string) *GetInsightByVersionParams {
	o.SetProjectOwner(projectOwner)
	return o
}

// SetProjectOwner adds the projectOwner to the get insight by version params
func (o *GetInsightByVersionParams) SetProjectOwner(projectOwner string) {
	o.ProjectOwner = projectOwner
}

// WithVersionID adds the versionID to the get insight by version params
func (o *GetInsightByVersionParams) WithVersionID(versionID string) *GetInsightByVersionParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the get insight by version params
func (o *GetInsightByVersionParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInsightByVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param projectId
	if err := r.SetPathParam("projectId", o.ProjectID); err != nil {
		return err
	}

	// path param projectOwner
	if err := r.SetPathParam("projectOwner", o.ProjectOwner); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
