// Code generated by go-swagger; DO NOT EDIT.

package requests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// DeleteRequestReader is a Reader for the DeleteRequest structure.
type DeleteRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteRequestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteRequestUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteRequestForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteRequestNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteRequestInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteRequestOK creates a DeleteRequestOK with default headers values
func NewDeleteRequestOK() *DeleteRequestOK {
	return &DeleteRequestOK{}
}

/* DeleteRequestOK describes a response with status code 200, with default header values.

Successfully retrieved dataset
*/
type DeleteRequestOK struct {
	Payload *models.SuccessMessageDto
}

func (o *DeleteRequestOK) Error() string {
	return fmt.Sprintf("[DELETE /requests/{requestid}][%d] deleteRequestOK  %+v", 200, o.Payload)
}
func (o *DeleteRequestOK) GetPayload() *models.SuccessMessageDto {
	return o.Payload
}

func (o *DeleteRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessMessageDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRequestBadRequest creates a DeleteRequestBadRequest with default headers values
func NewDeleteRequestBadRequest() *DeleteRequestBadRequest {
	return &DeleteRequestBadRequest{}
}

/* DeleteRequestBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type DeleteRequestBadRequest struct {
	Payload *models.ErrorMessage
}

func (o *DeleteRequestBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /requests/{requestid}][%d] deleteRequestBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteRequestBadRequest) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteRequestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRequestUnauthorized creates a DeleteRequestUnauthorized with default headers values
func NewDeleteRequestUnauthorized() *DeleteRequestUnauthorized {
	return &DeleteRequestUnauthorized{}
}

/* DeleteRequestUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteRequestUnauthorized struct {
	Payload *models.ErrorMessage
}

func (o *DeleteRequestUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /requests/{requestid}][%d] deleteRequestUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteRequestUnauthorized) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteRequestUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRequestForbidden creates a DeleteRequestForbidden with default headers values
func NewDeleteRequestForbidden() *DeleteRequestForbidden {
	return &DeleteRequestForbidden{}
}

/* DeleteRequestForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteRequestForbidden struct {
	Payload *models.ErrorMessage
}

func (o *DeleteRequestForbidden) Error() string {
	return fmt.Sprintf("[DELETE /requests/{requestid}][%d] deleteRequestForbidden  %+v", 403, o.Payload)
}
func (o *DeleteRequestForbidden) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteRequestForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRequestNotFound creates a DeleteRequestNotFound with default headers values
func NewDeleteRequestNotFound() *DeleteRequestNotFound {
	return &DeleteRequestNotFound{}
}

/* DeleteRequestNotFound describes a response with status code 404, with default header values.

Not found
*/
type DeleteRequestNotFound struct {
	Payload *models.ErrorMessage
}

func (o *DeleteRequestNotFound) Error() string {
	return fmt.Sprintf("[DELETE /requests/{requestid}][%d] deleteRequestNotFound  %+v", 404, o.Payload)
}
func (o *DeleteRequestNotFound) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteRequestNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteRequestInternalServerError creates a DeleteRequestInternalServerError with default headers values
func NewDeleteRequestInternalServerError() *DeleteRequestInternalServerError {
	return &DeleteRequestInternalServerError{}
}

/* DeleteRequestInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type DeleteRequestInternalServerError struct {
	Payload *models.ErrorMessage
}

func (o *DeleteRequestInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /requests/{requestid}][%d] deleteRequestInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteRequestInternalServerError) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DeleteRequestInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
