// Code generated by go-swagger; DO NOT EDIT.

package requests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRequestsParams creates a new GetRequestsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRequestsParams() *GetRequestsParams {
	return &GetRequestsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRequestsParamsWithTimeout creates a new GetRequestsParams object
// with the ability to set a timeout on a request.
func NewGetRequestsParamsWithTimeout(timeout time.Duration) *GetRequestsParams {
	return &GetRequestsParams{
		timeout: timeout,
	}
}

// NewGetRequestsParamsWithContext creates a new GetRequestsParams object
// with the ability to set a context for a request.
func NewGetRequestsParamsWithContext(ctx context.Context) *GetRequestsParams {
	return &GetRequestsParams{
		Context: ctx,
	}
}

// NewGetRequestsParamsWithHTTPClient creates a new GetRequestsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRequestsParamsWithHTTPClient(client *http.Client) *GetRequestsParams {
	return &GetRequestsParams{
		HTTPClient: client,
	}
}

/* GetRequestsParams contains all the parameters to send to the API endpoint
   for the get requests operation.

   Typically these are written to a http.Request.
*/
type GetRequestsParams struct {

	// Agentid.
	Agentid string

	// Limit.
	Limit *string

	// Next.
	Next *string

	// Sort.
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get requests params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRequestsParams) WithDefaults() *GetRequestsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get requests params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRequestsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get requests params
func (o *GetRequestsParams) WithTimeout(timeout time.Duration) *GetRequestsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get requests params
func (o *GetRequestsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get requests params
func (o *GetRequestsParams) WithContext(ctx context.Context) *GetRequestsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get requests params
func (o *GetRequestsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get requests params
func (o *GetRequestsParams) WithHTTPClient(client *http.Client) *GetRequestsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get requests params
func (o *GetRequestsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentid adds the agentid to the get requests params
func (o *GetRequestsParams) WithAgentid(agentid string) *GetRequestsParams {
	o.SetAgentid(agentid)
	return o
}

// SetAgentid adds the agentid to the get requests params
func (o *GetRequestsParams) SetAgentid(agentid string) {
	o.Agentid = agentid
}

// WithLimit adds the limit to the get requests params
func (o *GetRequestsParams) WithLimit(limit *string) *GetRequestsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get requests params
func (o *GetRequestsParams) SetLimit(limit *string) {
	o.Limit = limit
}

// WithNext adds the next to the get requests params
func (o *GetRequestsParams) WithNext(next *string) *GetRequestsParams {
	o.SetNext(next)
	return o
}

// SetNext adds the next to the get requests params
func (o *GetRequestsParams) SetNext(next *string) {
	o.Next = next
}

// WithSort adds the sort to the get requests params
func (o *GetRequestsParams) WithSort(sort *string) *GetRequestsParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get requests params
func (o *GetRequestsParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetRequestsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agentid
	if err := r.SetPathParam("agentid", o.Agentid); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit string

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := qrLimit
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Next != nil {

		// query param next
		var qrNext string

		if o.Next != nil {
			qrNext = *o.Next
		}
		qNext := qrNext
		if qNext != "" {

			if err := r.SetQueryParam("next", qNext); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
