// Code generated by go-swagger; DO NOT EDIT.

package partners

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStitchAuthorizedParams creates a new StitchAuthorizedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStitchAuthorizedParams() *StitchAuthorizedParams {
	return &StitchAuthorizedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStitchAuthorizedParamsWithTimeout creates a new StitchAuthorizedParams object
// with the ability to set a timeout on a request.
func NewStitchAuthorizedParamsWithTimeout(timeout time.Duration) *StitchAuthorizedParams {
	return &StitchAuthorizedParams{
		timeout: timeout,
	}
}

// NewStitchAuthorizedParamsWithContext creates a new StitchAuthorizedParams object
// with the ability to set a context for a request.
func NewStitchAuthorizedParamsWithContext(ctx context.Context) *StitchAuthorizedParams {
	return &StitchAuthorizedParams{
		Context: ctx,
	}
}

// NewStitchAuthorizedParamsWithHTTPClient creates a new StitchAuthorizedParams object
// with the ability to set a custom HTTPClient for a request.
func NewStitchAuthorizedParamsWithHTTPClient(client *http.Client) *StitchAuthorizedParams {
	return &StitchAuthorizedParams{
		HTTPClient: client,
	}
}

/* StitchAuthorizedParams contains all the parameters to send to the API endpoint
   for the stitch authorized operation.

   Typically these are written to a http.Request.
*/
type StitchAuthorizedParams struct {

	// Account.
	Account string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stitch authorized params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StitchAuthorizedParams) WithDefaults() *StitchAuthorizedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stitch authorized params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StitchAuthorizedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stitch authorized params
func (o *StitchAuthorizedParams) WithTimeout(timeout time.Duration) *StitchAuthorizedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stitch authorized params
func (o *StitchAuthorizedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stitch authorized params
func (o *StitchAuthorizedParams) WithContext(ctx context.Context) *StitchAuthorizedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stitch authorized params
func (o *StitchAuthorizedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stitch authorized params
func (o *StitchAuthorizedParams) WithHTTPClient(client *http.Client) *StitchAuthorizedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stitch authorized params
func (o *StitchAuthorizedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccount adds the account to the stitch authorized params
func (o *StitchAuthorizedParams) WithAccount(account string) *StitchAuthorizedParams {
	o.SetAccount(account)
	return o
}

// SetAccount adds the account to the stitch authorized params
func (o *StitchAuthorizedParams) SetAccount(account string) {
	o.Account = account
}

// WriteToRequest writes these params to a swagger request
func (o *StitchAuthorizedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account
	if err := r.SetPathParam("account", o.Account); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
