// Code generated by go-swagger; DO NOT EDIT.

package analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// CreateCatalogAnalysisReader is a Reader for the CreateCatalogAnalysis structure.
type CreateCatalogAnalysisReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCatalogAnalysisReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCatalogAnalysisOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateCatalogAnalysisBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateCatalogAnalysisUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateCatalogAnalysisForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateCatalogAnalysisNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateCatalogAnalysisConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewCreateCatalogAnalysisUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateCatalogAnalysisInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateCatalogAnalysisOK creates a CreateCatalogAnalysisOK with default headers values
func NewCreateCatalogAnalysisOK() *CreateCatalogAnalysisOK {
	return &CreateCatalogAnalysisOK{}
}

/* CreateCatalogAnalysisOK describes a response with status code 200, with default header values.

Analysis Metadata created successfully.
*/
type CreateCatalogAnalysisOK struct {
	Payload *models.CreateResponse
}

func (o *CreateCatalogAnalysisOK) Error() string {
	return fmt.Sprintf("[POST /metadata/analysis/{owner}][%d] createCatalogAnalysisOK  %+v", 200, o.Payload)
}
func (o *CreateCatalogAnalysisOK) GetPayload() *models.CreateResponse {
	return o.Payload
}

func (o *CreateCatalogAnalysisOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCatalogAnalysisBadRequest creates a CreateCatalogAnalysisBadRequest with default headers values
func NewCreateCatalogAnalysisBadRequest() *CreateCatalogAnalysisBadRequest {
	return &CreateCatalogAnalysisBadRequest{}
}

/* CreateCatalogAnalysisBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateCatalogAnalysisBadRequest struct {
	Payload *models.ErrorMessage
}

func (o *CreateCatalogAnalysisBadRequest) Error() string {
	return fmt.Sprintf("[POST /metadata/analysis/{owner}][%d] createCatalogAnalysisBadRequest  %+v", 400, o.Payload)
}
func (o *CreateCatalogAnalysisBadRequest) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateCatalogAnalysisBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCatalogAnalysisUnauthorized creates a CreateCatalogAnalysisUnauthorized with default headers values
func NewCreateCatalogAnalysisUnauthorized() *CreateCatalogAnalysisUnauthorized {
	return &CreateCatalogAnalysisUnauthorized{}
}

/* CreateCatalogAnalysisUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateCatalogAnalysisUnauthorized struct {
	Payload *models.ErrorMessage
}

func (o *CreateCatalogAnalysisUnauthorized) Error() string {
	return fmt.Sprintf("[POST /metadata/analysis/{owner}][%d] createCatalogAnalysisUnauthorized  %+v", 401, o.Payload)
}
func (o *CreateCatalogAnalysisUnauthorized) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateCatalogAnalysisUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCatalogAnalysisForbidden creates a CreateCatalogAnalysisForbidden with default headers values
func NewCreateCatalogAnalysisForbidden() *CreateCatalogAnalysisForbidden {
	return &CreateCatalogAnalysisForbidden{}
}

/* CreateCatalogAnalysisForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateCatalogAnalysisForbidden struct {
	Payload *models.ErrorMessage
}

func (o *CreateCatalogAnalysisForbidden) Error() string {
	return fmt.Sprintf("[POST /metadata/analysis/{owner}][%d] createCatalogAnalysisForbidden  %+v", 403, o.Payload)
}
func (o *CreateCatalogAnalysisForbidden) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateCatalogAnalysisForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCatalogAnalysisNotFound creates a CreateCatalogAnalysisNotFound with default headers values
func NewCreateCatalogAnalysisNotFound() *CreateCatalogAnalysisNotFound {
	return &CreateCatalogAnalysisNotFound{}
}

/* CreateCatalogAnalysisNotFound describes a response with status code 404, with default header values.

Not found
*/
type CreateCatalogAnalysisNotFound struct {
	Payload *models.ErrorMessage
}

func (o *CreateCatalogAnalysisNotFound) Error() string {
	return fmt.Sprintf("[POST /metadata/analysis/{owner}][%d] createCatalogAnalysisNotFound  %+v", 404, o.Payload)
}
func (o *CreateCatalogAnalysisNotFound) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateCatalogAnalysisNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCatalogAnalysisConflict creates a CreateCatalogAnalysisConflict with default headers values
func NewCreateCatalogAnalysisConflict() *CreateCatalogAnalysisConflict {
	return &CreateCatalogAnalysisConflict{}
}

/* CreateCatalogAnalysisConflict describes a response with status code 409, with default header values.

Conflict
*/
type CreateCatalogAnalysisConflict struct {
	Payload *models.ErrorMessage
}

func (o *CreateCatalogAnalysisConflict) Error() string {
	return fmt.Sprintf("[POST /metadata/analysis/{owner}][%d] createCatalogAnalysisConflict  %+v", 409, o.Payload)
}
func (o *CreateCatalogAnalysisConflict) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateCatalogAnalysisConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCatalogAnalysisUnprocessableEntity creates a CreateCatalogAnalysisUnprocessableEntity with default headers values
func NewCreateCatalogAnalysisUnprocessableEntity() *CreateCatalogAnalysisUnprocessableEntity {
	return &CreateCatalogAnalysisUnprocessableEntity{}
}

/* CreateCatalogAnalysisUnprocessableEntity describes a response with status code 422, with default header values.

Bad request
*/
type CreateCatalogAnalysisUnprocessableEntity struct {
	Payload *models.ErrorMessage
}

func (o *CreateCatalogAnalysisUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /metadata/analysis/{owner}][%d] createCatalogAnalysisUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *CreateCatalogAnalysisUnprocessableEntity) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateCatalogAnalysisUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateCatalogAnalysisInternalServerError creates a CreateCatalogAnalysisInternalServerError with default headers values
func NewCreateCatalogAnalysisInternalServerError() *CreateCatalogAnalysisInternalServerError {
	return &CreateCatalogAnalysisInternalServerError{}
}

/* CreateCatalogAnalysisInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type CreateCatalogAnalysisInternalServerError struct {
	Payload *models.ErrorMessage
}

func (o *CreateCatalogAnalysisInternalServerError) Error() string {
	return fmt.Sprintf("[POST /metadata/analysis/{owner}][%d] createCatalogAnalysisInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateCatalogAnalysisInternalServerError) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateCatalogAnalysisInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
