// Code generated by go-swagger; DO NOT EDIT.

package analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteCatalogAnalysisParams creates a new DeleteCatalogAnalysisParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCatalogAnalysisParams() *DeleteCatalogAnalysisParams {
	return &DeleteCatalogAnalysisParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCatalogAnalysisParamsWithTimeout creates a new DeleteCatalogAnalysisParams object
// with the ability to set a timeout on a request.
func NewDeleteCatalogAnalysisParamsWithTimeout(timeout time.Duration) *DeleteCatalogAnalysisParams {
	return &DeleteCatalogAnalysisParams{
		timeout: timeout,
	}
}

// NewDeleteCatalogAnalysisParamsWithContext creates a new DeleteCatalogAnalysisParams object
// with the ability to set a context for a request.
func NewDeleteCatalogAnalysisParamsWithContext(ctx context.Context) *DeleteCatalogAnalysisParams {
	return &DeleteCatalogAnalysisParams{
		Context: ctx,
	}
}

// NewDeleteCatalogAnalysisParamsWithHTTPClient creates a new DeleteCatalogAnalysisParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCatalogAnalysisParamsWithHTTPClient(client *http.Client) *DeleteCatalogAnalysisParams {
	return &DeleteCatalogAnalysisParams{
		HTTPClient: client,
	}
}

/* DeleteCatalogAnalysisParams contains all the parameters to send to the API endpoint
   for the delete catalog analysis operation.

   Typically these are written to a http.Request.
*/
type DeleteCatalogAnalysisParams struct {

	// ID.
	ID string

	// Owner.
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete catalog analysis params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCatalogAnalysisParams) WithDefaults() *DeleteCatalogAnalysisParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete catalog analysis params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCatalogAnalysisParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) WithTimeout(timeout time.Duration) *DeleteCatalogAnalysisParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) WithContext(ctx context.Context) *DeleteCatalogAnalysisParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) WithHTTPClient(client *http.Client) *DeleteCatalogAnalysisParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) WithID(id string) *DeleteCatalogAnalysisParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) WithOwner(owner string) *DeleteCatalogAnalysisParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the delete catalog analysis params
func (o *DeleteCatalogAnalysisParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCatalogAnalysisParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
