// Code generated by go-swagger; DO NOT EDIT.

package analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCatalogAnalysesByOwnerParams creates a new GetCatalogAnalysesByOwnerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCatalogAnalysesByOwnerParams() *GetCatalogAnalysesByOwnerParams {
	return &GetCatalogAnalysesByOwnerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCatalogAnalysesByOwnerParamsWithTimeout creates a new GetCatalogAnalysesByOwnerParams object
// with the ability to set a timeout on a request.
func NewGetCatalogAnalysesByOwnerParamsWithTimeout(timeout time.Duration) *GetCatalogAnalysesByOwnerParams {
	return &GetCatalogAnalysesByOwnerParams{
		timeout: timeout,
	}
}

// NewGetCatalogAnalysesByOwnerParamsWithContext creates a new GetCatalogAnalysesByOwnerParams object
// with the ability to set a context for a request.
func NewGetCatalogAnalysesByOwnerParamsWithContext(ctx context.Context) *GetCatalogAnalysesByOwnerParams {
	return &GetCatalogAnalysesByOwnerParams{
		Context: ctx,
	}
}

// NewGetCatalogAnalysesByOwnerParamsWithHTTPClient creates a new GetCatalogAnalysesByOwnerParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCatalogAnalysesByOwnerParamsWithHTTPClient(client *http.Client) *GetCatalogAnalysesByOwnerParams {
	return &GetCatalogAnalysesByOwnerParams{
		HTTPClient: client,
	}
}

/* GetCatalogAnalysesByOwnerParams contains all the parameters to send to the API endpoint
   for the get catalog analyses by owner operation.

   Typically these are written to a http.Request.
*/
type GetCatalogAnalysesByOwnerParams struct {

	// From.
	From *string

	// Owner.
	Owner string

	// Size.
	Size *string

	// Sort.
	Sort *string

	// Typeiri.
	Typeiri *string

	// Typelabel.
	Typelabel *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get catalog analyses by owner params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCatalogAnalysesByOwnerParams) WithDefaults() *GetCatalogAnalysesByOwnerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get catalog analyses by owner params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCatalogAnalysesByOwnerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithTimeout(timeout time.Duration) *GetCatalogAnalysesByOwnerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithContext(ctx context.Context) *GetCatalogAnalysesByOwnerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithHTTPClient(client *http.Client) *GetCatalogAnalysesByOwnerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithFrom(from *string) *GetCatalogAnalysesByOwnerParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetFrom(from *string) {
	o.From = from
}

// WithOwner adds the owner to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithOwner(owner string) *GetCatalogAnalysesByOwnerParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithSize adds the size to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithSize(size *string) *GetCatalogAnalysesByOwnerParams {
	o.SetSize(size)
	return o
}

// SetSize adds the size to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetSize(size *string) {
	o.Size = size
}

// WithSort adds the sort to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithSort(sort *string) *GetCatalogAnalysesByOwnerParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithTypeiri adds the typeiri to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithTypeiri(typeiri *string) *GetCatalogAnalysesByOwnerParams {
	o.SetTypeiri(typeiri)
	return o
}

// SetTypeiri adds the typeiri to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetTypeiri(typeiri *string) {
	o.Typeiri = typeiri
}

// WithTypelabel adds the typelabel to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) WithTypelabel(typelabel *string) *GetCatalogAnalysesByOwnerParams {
	o.SetTypelabel(typelabel)
	return o
}

// SetTypelabel adds the typelabel to the get catalog analyses by owner params
func (o *GetCatalogAnalysesByOwnerParams) SetTypelabel(typelabel *string) {
	o.Typelabel = typelabel
}

// WriteToRequest writes these params to a swagger request
func (o *GetCatalogAnalysesByOwnerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.From != nil {

		// query param from
		var qrFrom string

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if o.Size != nil {

		// query param size
		var qrSize string

		if o.Size != nil {
			qrSize = *o.Size
		}
		qSize := qrSize
		if qSize != "" {

			if err := r.SetQueryParam("size", qSize); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	if o.Typeiri != nil {

		// query param typeiri
		var qrTypeiri string

		if o.Typeiri != nil {
			qrTypeiri = *o.Typeiri
		}
		qTypeiri := qrTypeiri
		if qTypeiri != "" {

			if err := r.SetQueryParam("typeiri", qTypeiri); err != nil {
				return err
			}
		}
	}

	if o.Typelabel != nil {

		// query param typelabel
		var qrTypelabel string

		if o.Typelabel != nil {
			qrTypelabel = *o.Typelabel
		}
		qTypelabel := qrTypelabel
		if qTypelabel != "" {

			if err := r.SetQueryParam("typelabel", qTypelabel); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
