// Code generated by go-swagger; DO NOT EDIT.

package analysis

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// ReplaceCatalogAnalysisReader is a Reader for the ReplaceCatalogAnalysis structure.
type ReplaceCatalogAnalysisReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReplaceCatalogAnalysisReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReplaceCatalogAnalysisOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewReplaceCatalogAnalysisBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewReplaceCatalogAnalysisUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewReplaceCatalogAnalysisForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewReplaceCatalogAnalysisNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewReplaceCatalogAnalysisUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewReplaceCatalogAnalysisInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewReplaceCatalogAnalysisOK creates a ReplaceCatalogAnalysisOK with default headers values
func NewReplaceCatalogAnalysisOK() *ReplaceCatalogAnalysisOK {
	return &ReplaceCatalogAnalysisOK{}
}

/* ReplaceCatalogAnalysisOK describes a response with status code 200, with default header values.

Analysis replaced successfully.
*/
type ReplaceCatalogAnalysisOK struct {
	Payload *models.SuccessMessage
}

func (o *ReplaceCatalogAnalysisOK) Error() string {
	return fmt.Sprintf("[PUT /metadata/analysis/{owner}/{id}][%d] replaceCatalogAnalysisOK  %+v", 200, o.Payload)
}
func (o *ReplaceCatalogAnalysisOK) GetPayload() *models.SuccessMessage {
	return o.Payload
}

func (o *ReplaceCatalogAnalysisOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCatalogAnalysisBadRequest creates a ReplaceCatalogAnalysisBadRequest with default headers values
func NewReplaceCatalogAnalysisBadRequest() *ReplaceCatalogAnalysisBadRequest {
	return &ReplaceCatalogAnalysisBadRequest{}
}

/* ReplaceCatalogAnalysisBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type ReplaceCatalogAnalysisBadRequest struct {
	Payload *models.ErrorMessage
}

func (o *ReplaceCatalogAnalysisBadRequest) Error() string {
	return fmt.Sprintf("[PUT /metadata/analysis/{owner}/{id}][%d] replaceCatalogAnalysisBadRequest  %+v", 400, o.Payload)
}
func (o *ReplaceCatalogAnalysisBadRequest) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ReplaceCatalogAnalysisBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCatalogAnalysisUnauthorized creates a ReplaceCatalogAnalysisUnauthorized with default headers values
func NewReplaceCatalogAnalysisUnauthorized() *ReplaceCatalogAnalysisUnauthorized {
	return &ReplaceCatalogAnalysisUnauthorized{}
}

/* ReplaceCatalogAnalysisUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ReplaceCatalogAnalysisUnauthorized struct {
	Payload *models.ErrorMessage
}

func (o *ReplaceCatalogAnalysisUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /metadata/analysis/{owner}/{id}][%d] replaceCatalogAnalysisUnauthorized  %+v", 401, o.Payload)
}
func (o *ReplaceCatalogAnalysisUnauthorized) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ReplaceCatalogAnalysisUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCatalogAnalysisForbidden creates a ReplaceCatalogAnalysisForbidden with default headers values
func NewReplaceCatalogAnalysisForbidden() *ReplaceCatalogAnalysisForbidden {
	return &ReplaceCatalogAnalysisForbidden{}
}

/* ReplaceCatalogAnalysisForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ReplaceCatalogAnalysisForbidden struct {
	Payload *models.ErrorMessage
}

func (o *ReplaceCatalogAnalysisForbidden) Error() string {
	return fmt.Sprintf("[PUT /metadata/analysis/{owner}/{id}][%d] replaceCatalogAnalysisForbidden  %+v", 403, o.Payload)
}
func (o *ReplaceCatalogAnalysisForbidden) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ReplaceCatalogAnalysisForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCatalogAnalysisNotFound creates a ReplaceCatalogAnalysisNotFound with default headers values
func NewReplaceCatalogAnalysisNotFound() *ReplaceCatalogAnalysisNotFound {
	return &ReplaceCatalogAnalysisNotFound{}
}

/* ReplaceCatalogAnalysisNotFound describes a response with status code 404, with default header values.

Not found
*/
type ReplaceCatalogAnalysisNotFound struct {
	Payload *models.ErrorMessage
}

func (o *ReplaceCatalogAnalysisNotFound) Error() string {
	return fmt.Sprintf("[PUT /metadata/analysis/{owner}/{id}][%d] replaceCatalogAnalysisNotFound  %+v", 404, o.Payload)
}
func (o *ReplaceCatalogAnalysisNotFound) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ReplaceCatalogAnalysisNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCatalogAnalysisUnprocessableEntity creates a ReplaceCatalogAnalysisUnprocessableEntity with default headers values
func NewReplaceCatalogAnalysisUnprocessableEntity() *ReplaceCatalogAnalysisUnprocessableEntity {
	return &ReplaceCatalogAnalysisUnprocessableEntity{}
}

/* ReplaceCatalogAnalysisUnprocessableEntity describes a response with status code 422, with default header values.

Bad request
*/
type ReplaceCatalogAnalysisUnprocessableEntity struct {
	Payload *models.ErrorMessage
}

func (o *ReplaceCatalogAnalysisUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /metadata/analysis/{owner}/{id}][%d] replaceCatalogAnalysisUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *ReplaceCatalogAnalysisUnprocessableEntity) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ReplaceCatalogAnalysisUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReplaceCatalogAnalysisInternalServerError creates a ReplaceCatalogAnalysisInternalServerError with default headers values
func NewReplaceCatalogAnalysisInternalServerError() *ReplaceCatalogAnalysisInternalServerError {
	return &ReplaceCatalogAnalysisInternalServerError{}
}

/* ReplaceCatalogAnalysisInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type ReplaceCatalogAnalysisInternalServerError struct {
	Payload *models.ErrorMessage
}

func (o *ReplaceCatalogAnalysisInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /metadata/analysis/{owner}/{id}][%d] replaceCatalogAnalysisInternalServerError  %+v", 500, o.Payload)
}
func (o *ReplaceCatalogAnalysisInternalServerError) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ReplaceCatalogAnalysisInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
