// Code generated by go-swagger; DO NOT EDIT.

package glossary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// NewPatchCatalogGlossaryParams creates a new PatchCatalogGlossaryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchCatalogGlossaryParams() *PatchCatalogGlossaryParams {
	return &PatchCatalogGlossaryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchCatalogGlossaryParamsWithTimeout creates a new PatchCatalogGlossaryParams object
// with the ability to set a timeout on a request.
func NewPatchCatalogGlossaryParamsWithTimeout(timeout time.Duration) *PatchCatalogGlossaryParams {
	return &PatchCatalogGlossaryParams{
		timeout: timeout,
	}
}

// NewPatchCatalogGlossaryParamsWithContext creates a new PatchCatalogGlossaryParams object
// with the ability to set a context for a request.
func NewPatchCatalogGlossaryParamsWithContext(ctx context.Context) *PatchCatalogGlossaryParams {
	return &PatchCatalogGlossaryParams{
		Context: ctx,
	}
}

// NewPatchCatalogGlossaryParamsWithHTTPClient creates a new PatchCatalogGlossaryParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchCatalogGlossaryParamsWithHTTPClient(client *http.Client) *PatchCatalogGlossaryParams {
	return &PatchCatalogGlossaryParams{
		HTTPClient: client,
	}
}

/* PatchCatalogGlossaryParams contains all the parameters to send to the API endpoint
   for the patch catalog glossary operation.

   Typically these are written to a http.Request.
*/
type PatchCatalogGlossaryParams struct {

	// Body.
	Body *models.CatalogGlossaryRequest

	// ID.
	ID string

	// Owner.
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch catalog glossary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchCatalogGlossaryParams) WithDefaults() *PatchCatalogGlossaryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch catalog glossary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchCatalogGlossaryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) WithTimeout(timeout time.Duration) *PatchCatalogGlossaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) WithContext(ctx context.Context) *PatchCatalogGlossaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) WithHTTPClient(client *http.Client) *PatchCatalogGlossaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) WithBody(body *models.CatalogGlossaryRequest) *PatchCatalogGlossaryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) SetBody(body *models.CatalogGlossaryRequest) {
	o.Body = body
}

// WithID adds the id to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) WithID(id string) *PatchCatalogGlossaryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) WithOwner(owner string) *PatchCatalogGlossaryParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the patch catalog glossary params
func (o *PatchCatalogGlossaryParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *PatchCatalogGlossaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
