// Code generated by go-swagger; DO NOT EDIT.

package glossary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// NewReplaceCatalogGlossaryParams creates a new ReplaceCatalogGlossaryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewReplaceCatalogGlossaryParams() *ReplaceCatalogGlossaryParams {
	return &ReplaceCatalogGlossaryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewReplaceCatalogGlossaryParamsWithTimeout creates a new ReplaceCatalogGlossaryParams object
// with the ability to set a timeout on a request.
func NewReplaceCatalogGlossaryParamsWithTimeout(timeout time.Duration) *ReplaceCatalogGlossaryParams {
	return &ReplaceCatalogGlossaryParams{
		timeout: timeout,
	}
}

// NewReplaceCatalogGlossaryParamsWithContext creates a new ReplaceCatalogGlossaryParams object
// with the ability to set a context for a request.
func NewReplaceCatalogGlossaryParamsWithContext(ctx context.Context) *ReplaceCatalogGlossaryParams {
	return &ReplaceCatalogGlossaryParams{
		Context: ctx,
	}
}

// NewReplaceCatalogGlossaryParamsWithHTTPClient creates a new ReplaceCatalogGlossaryParams object
// with the ability to set a custom HTTPClient for a request.
func NewReplaceCatalogGlossaryParamsWithHTTPClient(client *http.Client) *ReplaceCatalogGlossaryParams {
	return &ReplaceCatalogGlossaryParams{
		HTTPClient: client,
	}
}

/* ReplaceCatalogGlossaryParams contains all the parameters to send to the API endpoint
   for the replace catalog glossary operation.

   Typically these are written to a http.Request.
*/
type ReplaceCatalogGlossaryParams struct {

	// Body.
	Body *models.CatalogGlossaryRequest

	// ID.
	ID string

	// Owner.
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the replace catalog glossary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceCatalogGlossaryParams) WithDefaults() *ReplaceCatalogGlossaryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the replace catalog glossary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ReplaceCatalogGlossaryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) WithTimeout(timeout time.Duration) *ReplaceCatalogGlossaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) WithContext(ctx context.Context) *ReplaceCatalogGlossaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) WithHTTPClient(client *http.Client) *ReplaceCatalogGlossaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) WithBody(body *models.CatalogGlossaryRequest) *ReplaceCatalogGlossaryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) SetBody(body *models.CatalogGlossaryRequest) {
	o.Body = body
}

// WithID adds the id to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) WithID(id string) *ReplaceCatalogGlossaryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) SetID(id string) {
	o.ID = id
}

// WithOwner adds the owner to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) WithOwner(owner string) *ReplaceCatalogGlossaryParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the replace catalog glossary params
func (o *ReplaceCatalogGlossaryParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *ReplaceCatalogGlossaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
