// Code generated by go-swagger; DO NOT EDIT.

package relationships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// CreateRelationshipReader is a Reader for the CreateRelationship structure.
type CreateRelationshipReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRelationshipReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateRelationshipOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateRelationshipBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateRelationshipUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateRelationshipForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateRelationshipNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateRelationshipInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateRelationshipOK creates a CreateRelationshipOK with default headers values
func NewCreateRelationshipOK() *CreateRelationshipOK {
	return &CreateRelationshipOK{}
}

/* CreateRelationshipOK describes a response with status code 200, with default header values.

successful operation
*/
type CreateRelationshipOK struct {
	Payload *models.EditActivitiesResultDto
}

func (o *CreateRelationshipOK) Error() string {
	return fmt.Sprintf("[POST /metadata/relationships/{owner}][%d] createRelationshipOK  %+v", 200, o.Payload)
}
func (o *CreateRelationshipOK) GetPayload() *models.EditActivitiesResultDto {
	return o.Payload
}

func (o *CreateRelationshipOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EditActivitiesResultDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRelationshipBadRequest creates a CreateRelationshipBadRequest with default headers values
func NewCreateRelationshipBadRequest() *CreateRelationshipBadRequest {
	return &CreateRelationshipBadRequest{}
}

/* CreateRelationshipBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type CreateRelationshipBadRequest struct {
	Payload *models.ErrorMessage
}

func (o *CreateRelationshipBadRequest) Error() string {
	return fmt.Sprintf("[POST /metadata/relationships/{owner}][%d] createRelationshipBadRequest  %+v", 400, o.Payload)
}
func (o *CreateRelationshipBadRequest) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateRelationshipBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRelationshipUnauthorized creates a CreateRelationshipUnauthorized with default headers values
func NewCreateRelationshipUnauthorized() *CreateRelationshipUnauthorized {
	return &CreateRelationshipUnauthorized{}
}

/* CreateRelationshipUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateRelationshipUnauthorized struct {
	Payload *models.ErrorMessage
}

func (o *CreateRelationshipUnauthorized) Error() string {
	return fmt.Sprintf("[POST /metadata/relationships/{owner}][%d] createRelationshipUnauthorized  %+v", 401, o.Payload)
}
func (o *CreateRelationshipUnauthorized) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateRelationshipUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRelationshipForbidden creates a CreateRelationshipForbidden with default headers values
func NewCreateRelationshipForbidden() *CreateRelationshipForbidden {
	return &CreateRelationshipForbidden{}
}

/* CreateRelationshipForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateRelationshipForbidden struct {
	Payload *models.ErrorMessage
}

func (o *CreateRelationshipForbidden) Error() string {
	return fmt.Sprintf("[POST /metadata/relationships/{owner}][%d] createRelationshipForbidden  %+v", 403, o.Payload)
}
func (o *CreateRelationshipForbidden) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateRelationshipForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRelationshipNotFound creates a CreateRelationshipNotFound with default headers values
func NewCreateRelationshipNotFound() *CreateRelationshipNotFound {
	return &CreateRelationshipNotFound{}
}

/* CreateRelationshipNotFound describes a response with status code 404, with default header values.

Not found
*/
type CreateRelationshipNotFound struct {
	Payload *models.ErrorMessage
}

func (o *CreateRelationshipNotFound) Error() string {
	return fmt.Sprintf("[POST /metadata/relationships/{owner}][%d] createRelationshipNotFound  %+v", 404, o.Payload)
}
func (o *CreateRelationshipNotFound) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateRelationshipNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRelationshipInternalServerError creates a CreateRelationshipInternalServerError with default headers values
func NewCreateRelationshipInternalServerError() *CreateRelationshipInternalServerError {
	return &CreateRelationshipInternalServerError{}
}

/* CreateRelationshipInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type CreateRelationshipInternalServerError struct {
	Payload *models.ErrorMessage
}

func (o *CreateRelationshipInternalServerError) Error() string {
	return fmt.Sprintf("[POST /metadata/relationships/{owner}][%d] createRelationshipInternalServerError  %+v", 500, o.Payload)
}
func (o *CreateRelationshipInternalServerError) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CreateRelationshipInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
