// Code generated by go-swagger; DO NOT EDIT.

package relationships

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"datadotworld-go-sdk/models"
)

// NewDeleteRelationshipParams creates a new DeleteRelationshipParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteRelationshipParams() *DeleteRelationshipParams {
	return &DeleteRelationshipParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRelationshipParamsWithTimeout creates a new DeleteRelationshipParams object
// with the ability to set a timeout on a request.
func NewDeleteRelationshipParamsWithTimeout(timeout time.Duration) *DeleteRelationshipParams {
	return &DeleteRelationshipParams{
		timeout: timeout,
	}
}

// NewDeleteRelationshipParamsWithContext creates a new DeleteRelationshipParams object
// with the ability to set a context for a request.
func NewDeleteRelationshipParamsWithContext(ctx context.Context) *DeleteRelationshipParams {
	return &DeleteRelationshipParams{
		Context: ctx,
	}
}

// NewDeleteRelationshipParamsWithHTTPClient creates a new DeleteRelationshipParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteRelationshipParamsWithHTTPClient(client *http.Client) *DeleteRelationshipParams {
	return &DeleteRelationshipParams{
		HTTPClient: client,
	}
}

/* DeleteRelationshipParams contains all the parameters to send to the API endpoint
   for the delete relationship operation.

   Typically these are written to a http.Request.
*/
type DeleteRelationshipParams struct {

	// Body.
	Body *models.RelationshipCreateOrDeleteRequest

	// Owner.
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete relationship params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRelationshipParams) WithDefaults() *DeleteRelationshipParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete relationship params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRelationshipParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete relationship params
func (o *DeleteRelationshipParams) WithTimeout(timeout time.Duration) *DeleteRelationshipParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete relationship params
func (o *DeleteRelationshipParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete relationship params
func (o *DeleteRelationshipParams) WithContext(ctx context.Context) *DeleteRelationshipParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete relationship params
func (o *DeleteRelationshipParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete relationship params
func (o *DeleteRelationshipParams) WithHTTPClient(client *http.Client) *DeleteRelationshipParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete relationship params
func (o *DeleteRelationshipParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete relationship params
func (o *DeleteRelationshipParams) WithBody(body *models.RelationshipCreateOrDeleteRequest) *DeleteRelationshipParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete relationship params
func (o *DeleteRelationshipParams) SetBody(body *models.RelationshipCreateOrDeleteRequest) {
	o.Body = body
}

// WithOwner adds the owner to the delete relationship params
func (o *DeleteRelationshipParams) WithOwner(owner string) *DeleteRelationshipParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the delete relationship params
func (o *DeleteRelationshipParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRelationshipParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
