// Code generated by go-swagger; DO NOT EDIT.

package cancel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCancelParams creates a new CancelParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCancelParams() *CancelParams {
	return &CancelParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCancelParamsWithTimeout creates a new CancelParams object
// with the ability to set a timeout on a request.
func NewCancelParamsWithTimeout(timeout time.Duration) *CancelParams {
	return &CancelParams{
		timeout: timeout,
	}
}

// NewCancelParamsWithContext creates a new CancelParams object
// with the ability to set a context for a request.
func NewCancelParamsWithContext(ctx context.Context) *CancelParams {
	return &CancelParams{
		Context: ctx,
	}
}

// NewCancelParamsWithHTTPClient creates a new CancelParams object
// with the ability to set a custom HTTPClient for a request.
func NewCancelParamsWithHTTPClient(client *http.Client) *CancelParams {
	return &CancelParams{
		HTTPClient: client,
	}
}

/* CancelParams contains all the parameters to send to the API endpoint
   for the cancel operation.

   Typically these are written to a http.Request.
*/
type CancelParams struct {

	// Queryruntoken.
	Queryruntoken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the cancel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CancelParams) WithDefaults() *CancelParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the cancel params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CancelParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the cancel params
func (o *CancelParams) WithTimeout(timeout time.Duration) *CancelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel params
func (o *CancelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel params
func (o *CancelParams) WithContext(ctx context.Context) *CancelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel params
func (o *CancelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel params
func (o *CancelParams) WithHTTPClient(client *http.Client) *CancelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel params
func (o *CancelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQueryruntoken adds the queryruntoken to the cancel params
func (o *CancelParams) WithQueryruntoken(queryruntoken *string) *CancelParams {
	o.SetQueryruntoken(queryruntoken)
	return o
}

// SetQueryruntoken adds the queryruntoken to the cancel params
func (o *CancelParams) SetQueryruntoken(queryruntoken *string) {
	o.Queryruntoken = queryruntoken
}

// WriteToRequest writes these params to a swagger request
func (o *CancelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Queryruntoken != nil {

		// query param queryruntoken
		var qrQueryruntoken string

		if o.Queryruntoken != nil {
			qrQueryruntoken = *o.Queryruntoken
		}
		qQueryruntoken := qrQueryruntoken
		if qQueryruntoken != "" {

			if err := r.SetQueryParam("queryruntoken", qQueryruntoken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
