// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AssetStatus asset status
//
// swagger:model AssetStatus
type AssetStatus struct {

	// asset status label
	AssetStatusLabel string `json:"assetStatusLabel,omitempty"`

	// disposition label
	DispositionLabel string `json:"dispositionLabel,omitempty"`
}

// Validate validates this asset status
func (m *AssetStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this asset status based on context it is used
func (m *AssetStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AssetStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetStatus) UnmarshalBinary(b []byte) error {
	var res AssetStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
