// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConceptEntry concept entry
//
// swagger:model ConceptEntry
type ConceptEntry struct {

	// alt label
	AltLabel string `json:"altLabel,omitempty"`

	// iri
	Iri string `json:"iri,omitempty"`

	// pref label
	PrefLabel string `json:"prefLabel,omitempty"`
}

// Validate validates this concept entry
func (m *ConceptEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this concept entry based on context it is used
func (m *ConceptEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConceptEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConceptEntry) UnmarshalBinary(b []byte) error {
	var res ConceptEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
