// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InsightSummaryResponse insight summary response
//
// swagger:model InsightSummaryResponse
type InsightSummaryResponse struct {

	// author
	// Required: true
	Author *string `json:"author"`

	// body
	// Required: true
	Body *InsightBody `json:"body"`

	// created
	// Required: true
	Created *string `json:"created"`

	// data source links
	DataSourceLinks []strfmt.URI `json:"dataSourceLinks"`

	// description
	// Max Length: 25000
	// Min Length: 0
	Description *string `json:"description,omitempty"`

	// id
	// Required: true
	ID *string `json:"id"`

	// source link
	// Format: uri
	SourceLink strfmt.URI `json:"sourceLink,omitempty"`

	// thumbnail
	// Format: uri
	Thumbnail strfmt.URI `json:"thumbnail,omitempty"`

	// title
	// Required: true
	// Max Length: 128
	// Min Length: 1
	Title *string `json:"title"`

	// updated
	// Required: true
	Updated *string `json:"updated"`

	// version
	// Required: true
	Version *string `json:"version"`
}

// Validate validates this insight summary response
func (m *InsightSummaryResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDataSourceLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSourceLink(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateThumbnail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InsightSummaryResponse) validateAuthor(formats strfmt.Registry) error {

	if err := validate.Required("author", "body", m.Author); err != nil {
		return err
	}

	return nil
}

func (m *InsightSummaryResponse) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("body", "body", m.Body); err != nil {
		return err
	}

	if m.Body != nil {
		if err := m.Body.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body")
			}
			return err
		}
	}

	return nil
}

func (m *InsightSummaryResponse) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("created", "body", m.Created); err != nil {
		return err
	}

	return nil
}

func (m *InsightSummaryResponse) validateDataSourceLinks(formats strfmt.Registry) error {
	if swag.IsZero(m.DataSourceLinks) { // not required
		return nil
	}

	for i := 0; i < len(m.DataSourceLinks); i++ {

		if err := validate.FormatOf("dataSourceLinks"+"."+strconv.Itoa(i), "body", "uri", m.DataSourceLinks[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

func (m *InsightSummaryResponse) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MinLength("description", "body", *m.Description, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("description", "body", *m.Description, 25000); err != nil {
		return err
	}

	return nil
}

func (m *InsightSummaryResponse) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *InsightSummaryResponse) validateSourceLink(formats strfmt.Registry) error {
	if swag.IsZero(m.SourceLink) { // not required
		return nil
	}

	if err := validate.FormatOf("sourceLink", "body", "uri", m.SourceLink.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *InsightSummaryResponse) validateThumbnail(formats strfmt.Registry) error {
	if swag.IsZero(m.Thumbnail) { // not required
		return nil
	}

	if err := validate.FormatOf("thumbnail", "body", "uri", m.Thumbnail.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *InsightSummaryResponse) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	if err := validate.MinLength("title", "body", *m.Title, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("title", "body", *m.Title, 128); err != nil {
		return err
	}

	return nil
}

func (m *InsightSummaryResponse) validateUpdated(formats strfmt.Registry) error {

	if err := validate.Required("updated", "body", m.Updated); err != nil {
		return err
	}

	return nil
}

func (m *InsightSummaryResponse) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this insight summary response based on the context it is used
func (m *InsightSummaryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBody(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InsightSummaryResponse) contextValidateBody(ctx context.Context, formats strfmt.Registry) error {

	if m.Body != nil {
		if err := m.Body.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InsightSummaryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InsightSummaryResponse) UnmarshalBinary(b []byte) error {
	var res InsightSummaryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
