// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResourceRelationshipDto resource relationship dto
//
// swagger:model ResourceRelationshipDto
type ResourceRelationshipDto struct {

	// contributor
	Contributor *bool `json:"contributor,omitempty"`

	// liked
	Liked *bool `json:"liked,omitempty"`
}

// Validate validates this resource relationship dto
func (m *ResourceRelationshipDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this resource relationship dto based on context it is used
func (m *ResourceRelationshipDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceRelationshipDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceRelationshipDto) UnmarshalBinary(b []byte) error {
	var res ResourceRelationshipDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
