// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TransferAssetDto transfer asset dto
//
// swagger:model TransferAssetDto
type TransferAssetDto struct {

	// entity type
	EntityType string `json:"entityType,omitempty"`

	// identifier
	Identifier string `json:"identifier,omitempty"`

	// iri
	Iri string `json:"iri,omitempty"`
}

// Validate validates this transfer asset dto
func (m *TransferAssetDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this transfer asset dto based on context it is used
func (m *TransferAssetDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransferAssetDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransferAssetDto) UnmarshalBinary(b []byte) error {
	var res TransferAssetDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
