// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UnknownCatalogEntryHydrationDto unknown catalog entry hydration dto
//
// swagger:model UnknownCatalogEntryHydrationDto
type UnknownCatalogEntryHydrationDto struct {

	// agentid
	Agentid string `json:"agentid,omitempty"`

	// asset status
	AssetStatus *AssetStatus `json:"assetStatus,omitempty"`

	// catalogs
	Catalogs []*CatalogID `json:"catalogs"`

	// created by
	CreatedBy *AgentHydrationDto `json:"createdBy,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// entry type hierarchy
	EntryTypeHierarchy []*EntryType `json:"entryTypeHierarchy"`

	// entry type label
	EntryTypeLabel string `json:"entryTypeLabel,omitempty"`

	// identifier
	Identifier string `json:"identifier,omitempty"`

	// referent
	Referent string `json:"referent,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// updated
	// Format: date-time
	Updated strfmt.DateTime `json:"updated,omitempty"`
}

// Validate validates this unknown catalog entry hydration dto
func (m *UnknownCatalogEntryHydrationDto) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssetStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCatalogs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEntryTypeHierarchy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnknownCatalogEntryHydrationDto) validateAssetStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.AssetStatus) { // not required
		return nil
	}

	if m.AssetStatus != nil {
		if err := m.AssetStatus.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("assetStatus")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("assetStatus")
			}
			return err
		}
	}

	return nil
}

func (m *UnknownCatalogEntryHydrationDto) validateCatalogs(formats strfmt.Registry) error {
	if swag.IsZero(m.Catalogs) { // not required
		return nil
	}

	for i := 0; i < len(m.Catalogs); i++ {
		if swag.IsZero(m.Catalogs[i]) { // not required
			continue
		}

		if m.Catalogs[i] != nil {
			if err := m.Catalogs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("catalogs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("catalogs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UnknownCatalogEntryHydrationDto) validateCreatedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedBy) { // not required
		return nil
	}

	if m.CreatedBy != nil {
		if err := m.CreatedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdBy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdBy")
			}
			return err
		}
	}

	return nil
}

func (m *UnknownCatalogEntryHydrationDto) validateEntryTypeHierarchy(formats strfmt.Registry) error {
	if swag.IsZero(m.EntryTypeHierarchy) { // not required
		return nil
	}

	for i := 0; i < len(m.EntryTypeHierarchy); i++ {
		if swag.IsZero(m.EntryTypeHierarchy[i]) { // not required
			continue
		}

		if m.EntryTypeHierarchy[i] != nil {
			if err := m.EntryTypeHierarchy[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entryTypeHierarchy" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("entryTypeHierarchy" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UnknownCatalogEntryHydrationDto) validateUpdated(formats strfmt.Registry) error {
	if swag.IsZero(m.Updated) { // not required
		return nil
	}

	if err := validate.FormatOf("updated", "body", "date-time", m.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this unknown catalog entry hydration dto based on the context it is used
func (m *UnknownCatalogEntryHydrationDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAssetStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCatalogs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEntryTypeHierarchy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UnknownCatalogEntryHydrationDto) contextValidateAssetStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.AssetStatus != nil {
		if err := m.AssetStatus.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("assetStatus")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("assetStatus")
			}
			return err
		}
	}

	return nil
}

func (m *UnknownCatalogEntryHydrationDto) contextValidateCatalogs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Catalogs); i++ {

		if m.Catalogs[i] != nil {
			if err := m.Catalogs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("catalogs" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("catalogs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UnknownCatalogEntryHydrationDto) contextValidateCreatedBy(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedBy != nil {
		if err := m.CreatedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdBy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdBy")
			}
			return err
		}
	}

	return nil
}

func (m *UnknownCatalogEntryHydrationDto) contextValidateEntryTypeHierarchy(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.EntryTypeHierarchy); i++ {

		if m.EntryTypeHierarchy[i] != nil {
			if err := m.EntryTypeHierarchy[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("entryTypeHierarchy" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("entryTypeHierarchy" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UnknownCatalogEntryHydrationDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UnknownCatalogEntryHydrationDto) UnmarshalBinary(b []byte) error {
	var res UnknownCatalogEntryHydrationDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
